name: HungerArena
main: me.travja.hungerarena.Main
api-version: 1.15
version: maven-version-number
description: A lightweight and powerful plugin to help with playing The Hunger Games!
depend: [WorldEdit]
softdepend: [Vault]
commands:
  ha:
    description: Makes you join a game or start the game!
  startpoint:
    description: Sets the starting point of a tribute.
  sponsor:
    description: Sponsors a Tribute